### ISSUE TITLE
Support paymaya 

### ISSUE THREAD

**Issue by paolotiu** [paolotiu/paymongo#2]
Paymongo recently added support for accepting Paymaya payments.

[Docs](https://developers.paymongo.com/docs/accepting-paymaya-payments)

**Comment by pdlozano** [comment]
Is someone working on this already? I’d like to work on it if there isn’t.

**Comment by paolotiu** [comment]
Yup, no one's working on it. Thank you so much for contributing :)

**Comment by pdlozano** [comment]
Hey, I just solved the issue and opened a PR. I wasn't able to update the documentation though to reflect the change.

**Comment by paolotiu** [comment]
closed #9
